version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      COMPANY_ID: ${COMPANY_ID}
    volumes:
      - .:/app
